name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger deployment only on push to the main branch
  pull_request:
    branches:
      - main  # Run checks on PRs, but don't deploy

jobs:
  # --- Build Frontend ---
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js for frontend
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version

    - name: Install frontend dependencies
      working-directory: ./frontend  # Navigate to the frontend folder
      run: npm install

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    - name: Upload frontend artifact
      uses: actions/upload-artifact@v4
      with:
        name: angular-build
        path: ./frontend/dist/  # Path to Angular build files

  # --- Build Backend ---
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js for backend
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify the Node.js version

    - name: Install backend dependencies
      working-directory: ./backend  # Navigate to the backend folder
      run: npm install

    - name: Upload backend artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-artifact
        path: ./backend  # Upload the backend folder for deployment

  # --- Deploy Frontend ---
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend  # Ensure the frontend build completes before deployment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download frontend artifact
      uses: actions/download-artifact@v4
      with:
        name: angular-build
        path: ./frontend/dist/smetovi/  # Download the Angular build

    - name: Deploy frontend to cPanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./frontend/dist/smetovi/  # Adjust this to match your project build output
        server-dir: /public_html/frontend/  # Path where frontend files are deployed on server
        port: ${{ secrets.FTP_PORT }}
        log-level: verbose
        delete: true  # Add this to clean the target directory before deploying

  # --- Deploy Backend ---
  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend  # Ensure the backend build completes before deployment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download backend artifact
      uses: actions/download-artifact@v4
      with:
        name: backend-artifact
        path: ./backend  # Download the backend code

    - name: Deploy backend to cPanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./backend/  # Adjust this to the correct backend build folder
        server-dir: /public_html/backend/  # Path where backend files are deployed on server
        port: ${{ secrets.FTP_PORT }}
        log-level: verbose
        delete: true  # Add this to clean the target directory before deploying
